# TCL File Generated by Component Editor 24.1
# Sat Apr 26 21:19:05 ICT 2025
# DO NOT MODIFY


# 
# top_avalon "top_avalon" v1.0
#  2025.04.26.21:19:05
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module top_avalon
# 
set_module_property DESCRIPTION ""
set_module_property NAME top_avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME top_avalon
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL top_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file top_avalon.v VERILOG PATH top_avalon.v TOP_LEVEL_FILE
add_fileset_file comparator.v VERILOG PATH ../cnn_verilog/comparator.v
add_fileset_file conv1_layer.v VERILOG PATH ../cnn_verilog/conv1_layer.v
add_fileset_file maxpool_relu.v VERILOG PATH ../cnn_verilog/maxpool_relu.v
add_fileset_file conv2_layer.v VERILOG PATH ../cnn_verilog/conv2_layer.v
add_fileset_file fully_connected.v VERILOG PATH ../cnn_verilog/fully_connected.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock ""
set_interface_property avalon_slave_0 associatedReset ""
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 iClk beginbursttransfer Input 1
add_interface_port avalon_slave_0 iReset_n beginbursttransfer Input 1
add_interface_port avalon_slave_0 iChipSelect_n beginbursttransfer Input 1
add_interface_port avalon_slave_0 iWrite_n beginbursttransfer Input 1
add_interface_port avalon_slave_0 iRead_n beginbursttransfer Input 1
add_interface_port avalon_slave_0 iAddress writebyteenable_n Input 2
add_interface_port avalon_slave_0 iData writebyteenable_n Input 32
add_interface_port avalon_slave_0 oData readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0

